version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/calendar
    ports:
      - 3000:3000
    image: app:calendarapp
    container_name: calendar_container
    command: npm start
